<a href="https://colab.research.google.com/github/JANG-hyeonjun/biomedical_deeplearning/blob/main/lab_01_201602955_%EC%9E%A5%ED%98%84%EC%A4%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

학번:201602955

이름:장현준 


Data manipulation 2.1


In [33]:
import torch

In [34]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
x.numel()

12

In [36]:
x.shape

torch.Size([12])

In [37]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

pytorch 를 이용해서 array의 개수 및 모양을 다양하게 바꿀수 있다는 점을 알수 있다 -> data를 다루기에 매운 좋은 tool임을 알 수 있다. 

In [38]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [39]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [40]:
torch.randn(3,4)

tensor([[-1.4840, -0.9554,  0.2742,  0.0790],
        [-0.4991, -0.5946, -0.0272,  0.1477],
        [ 0.2704,  1.4632, -0.6553, -0.4603]])

In [41]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

initlization 할 때 사용하면 좋을 것같다. 

In [42]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y  

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [43]:
torch.exp(x)
torch.cos(x)
print(torch.cos(x**2 + 2* x))
caculus = x **2 + 2 *x
print(torch.cos(caculus))

tensor([-0.9900, -0.1455,  0.4242, -0.1104])
tensor([-0.9900, -0.1455,  0.4242, -0.1104])


수식을 어떤 변수로 삼아서 저장할수 도 있고 다양한 계산을  차원 이 많은 텐서에대해 모두 적용할 수있다는점 이 중요하고 편리한 기능 같다.
 

In [44]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y), dim = 0),torch.cat((X,Y),dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [45]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [46]:
X.sum()

tensor(66.)

dim 을 기준으로 행차원 아니면 열차원에서 텐서들에대해 cat과 같은 연산을 할수 있다. 하지만 cat연산은 테스팅 결과 텐서들의 차원이 같아야 연산이 됨을 확인 할 수 있었다. 

In [47]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [48]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

broad casting을 파악할 수 있다. 수업시간의 내용을 상기시켜보면 브로드 캐스팅은 모양이 다른 텐서들의 계산을 도와주기도 하지만 의도 하지 않은 연산이 일어날 수 있음을 항상 주의 하라 하셨다.

In [49]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [50]:
X[1,2] = 9 
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [51]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

파이썬 에서의 인덱싱과 슬라이싱을 다시 짚어볼 수 있었다.


In [52]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [53]:
Z = torch.zeros_like(Y)
print(Z)
print(Y.shape)
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
id(Z): 140549071273488
id(Z): 140549071273488


In [54]:
before = id(X)
X += Y
id(X) == before

True

메모리를 절약할수 있는 방법을 파악할 수 있었다. 
그냥 변수를 X = X + Y로 하면 X+Y를 할당해주는 부분이 존재하는데 슬라이싱이나 += 같은 연산을 사용하면 메모리를 절약함을 알 수 있다.
zeros_like는 아무래도 Y의 텐서를 shpae을 그대로 가져와 0으로 초기화해준것을 알 수 있었다.



---------Conversion to to other Python Objects-----------


In [55]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [56]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

다양한 데이터를 텐서로 바꾸기 쉽다는것을 파악할수 있었다. 
위 와 같이 잘변경되면 Pandas나 다양한 툴로 가져온 데이터를 텐서로 manipulation을 쉽게 할 수 있다. 

2.1 Data_processing

In [57]:
pwd

'/content'

In [58]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')  # Column names
    f.write('NA,Pave,127500\n')  # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


In [59]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


위의 pwd를 이용해 현재경로를 파악한 결과 /content를 알수 있다. 

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv') 는 현재경로 부모 경로에 있는 곳에 data라는 directory를 만들고 그안에 집의 정보를 저장할 house_tiny.csv를 저장한것을 알 수 있다. 그런뒤 판다스 모듈을 이용해 csv파일을 읽어 print한 것임을 알 수 있다.

-----------Handling Missing data-----------

In [60]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [61]:
inputs = pd.get_dummies(inputs,dummy_na= True)
print(inputs)
print(type(inputs.values))

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1
<class 'numpy.ndarray'>


pave 와 nan은 서로간의 관계성이 필요 없으므로 
pandas의 get_dummies를 이용해 카테고리적이게 구분하는 코드이다.

---------Conversion to the Tensor Format-------

In [62]:
import torch 
X,y = torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

위에서 inputs.values의 type을 프린트 해본 결과 
numpy 의 ndarray형식임을 알 수 있었다. 
딥러닝을 pytorch 형식으로 해야하므로 numpy를 torch로 변경해주는것을 알 수 있다. 
 

2.3 linear-algebra


In [63]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y,x * y,x /y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

하나의 숫자로 나타낼수있는 scalars 를 나타내는 부분  

In [64]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [65]:
x[3]

tensor(3)

Vector에 대한 부분을 다음과 같이 적용 시킬수 있다.

In [66]:
len(x)

4

In [67]:
x.shape

torch.Size([4])

In [68]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [69]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [70]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [72]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Matrices 와 tranpose연산을 확인 할 수 있었다.

In [73]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [75]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [76]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [77]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

주어진 텐서의 크기가 같을경우 결과적으로 연산의 결과는 같은 모양을 유지한다는것을 알 수 있으며 이렇게 size 같거나 broad casting이 적용 되었을때 elementwise multiplication을 Hadmard product라고 한다. 

----------Reduction---------

In [79]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [81]:
print(A.shape)
print(A.sum())
print(A)


torch.Size([5, 4])
tensor(190.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [83]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [85]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1 ,A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [87]:
A_sum_axis2 = A.sum(axis = -1)
A_sum_axis2 ,A_sum_axis2.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [89]:
 print(A.sum(axis=[0,1]))
 print(A.sum(axis=[0,-1]))

tensor(190.)
tensor(190.)


Reduction은 dimension을 줄인다고 볼 수 있으며 위의 코드는 어떤 행 또는 열을 기준으로 덧셈으로 압축을 했다 볼 수 있다. 첫번쨰 차원 행 두번째는 열이므로 -1은 마지막 차원 즉 열을 가리킨다고 볼 수 있다.

In [90]:
A.mean(),A.sum()/ A.numel()

(tensor(9.5000), tensor(9.5000))

In [93]:
A.mean(axis=0),A.sum(axis=0)/ A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

Reduction의 방벙중 mean 애 관해서 일어나는 원리가 적혀 있다고 볼 수 있습니다.

In [95]:
sum_A = A.sum(axis=1,keepdims= True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [96]:
A /sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [97]:
A.cumsum(axis =0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])