<a href="https://colab.research.google.com/github/JANG-hyeonjun/biomedical_deeplearning/blob/main/lab_01_201602955_%EC%9E%A5%ED%98%84%EC%A4%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

학번:201602955

이름:장현준 


Data manipulation 2.1


In [ ]:
import torch

In [ ]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.numel()

12

In [ ]:
x.shape

torch.Size([12])

In [ ]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

pytorch 를 이용해서 array의 개수 및 모양을 다양하게 바꿀수 있다는 점을 알수 있다 -> data를 다루기에 매운 좋은 tool임을 알 수 있다. 

In [ ]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.randn(3,4)

tensor([[-0.0895, -1.1139,  1.5280, -0.7191],
        [-0.3174, -0.1479, -2.1027,  1.5309],
        [ 1.2167, -0.0678, -1.3941,  0.0047]])

In [ ]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

initlization 할 때 사용하면 좋을 것같다. 

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y  

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
torch.exp(x)
torch.cos(x)
print(torch.cos(x**2 + 2* x))
caculus = x **2 + 2 *x
print(torch.cos(caculus))

tensor([-0.9900, -0.1455,  0.4242, -0.1104])
tensor([-0.9900, -0.1455,  0.4242, -0.1104])


수식을 어떤 변수로 삼아서 저장할수 도 있고 다양한 계산을  차원 이 많은 텐서에대해 모두 적용할 수있다는점 이 중요하고 편리한 기능 같다.
 

In [ ]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y), dim = 0),torch.cat((X,Y),dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X.sum()

tensor(66.)

dim 을 기준으로 행차원 아니면 열차원에서 텐서들에대해 cat과 같은 연산을 할수 있다. 하지만 cat연산은 테스팅 결과 텐서들의 차원이 같아야 연산이 됨을 확인 할 수 있었다. 

In [ ]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [ ]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

broad casting을 파악할 수 있다. 수업시간의 내용을 상기시켜보면 브로드 캐스팅은 모양이 다른 텐서들의 계산을 도와주기도 하지만 의도 하지 않은 연산이 일어날 수 있음을 항상 주의 하라 하셨다.

In [ ]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
X[1,2] = 9 
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

파이썬 에서의 인덱싱과 슬라이싱을 다시 짚어볼 수 있었다.


In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [ ]:
Z = torch.zeros_like(Y)
print(Z)
print(Y.shape)
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
id(Z): 140357240152864
id(Z): 140357240152864


In [ ]:
before = id(X)
X += Y
id(X) == before

True

메모리를 절약할수 있는 방법을 파악할 수 있었다. 
그냥 변수를 X = X + Y로 하면 X+Y를 할당해주는 부분이 존재하는데 슬라이싱이나 += 같은 연산을 사용하면 메모리를 절약함을 알 수 있다.
zeros_like는 아무래도 Y의 텐서를 shpae을 그대로 가져와 0으로 초기화해준것을 알 수 있었다.



---------Conversion to to other Python Objects-----------


In [ ]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

다양한 데이터를 텐서로 바꾸기 쉽다는것을 파악할수 있었다. 
위 와 같이 잘변경되면 Pandas나 다양한 툴로 가져온 데이터를 텐서로 manipulation을 쉽게 할 수 있다. 